version: "4.3.1"

services:
  nginx:
    build:
      context: .
      dockerfile: docker/Nginx.Dockerfile
    ports:
      - 8098:80
    links:
      - fpm
    volumes:
      - ./:/var/www/job_RESTFull_API_Lumen
  fpm:
    build:
      context: .
      dockerfile: docker/Fpm.Dockerfile
    volumes:
      - ./:/var/www/job_RESTFull_API_Lumen
    links:
      - postgres
  postgres:
    image: postgres:11.5
    ports:
      - 5436:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
      - ./docker/conf/postgresql.conf:/usr/share/postgresql/postgresql.conf

volumes:
    pgdata:
      driver: local
    pgconf:
      driver: local
    pglog:
      driver: local
